# Generated by Django 5.0.6 on 2024-05-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Graph',
        ),
    ]
