# Generated by Django 5.0.6 on 2024-06-06 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0002_delete_graph'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_value', models.FloatField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexes', to='real_estate_app.district')),
            ],
            options={
                'db_table': 'real_estate_app_fear_greed_index',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='real_estate_app.region'),
        ),
        migrations.CreateModel(
            name='Momentum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=6)),
                ('momentum', models.FloatField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momentums', to='real_estate_app.district')),
            ],
            options={
                'db_table': 'real_estate_app_momentum',
                'unique_together': {('district', 'year_month')},
            },
        ),
        migrations.CreateModel(
            name='SentimentIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=6)),
                ('index_value', models.FloatField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_indexes', to='real_estate_app.district')),
            ],
            options={
                'db_table': 'real_estate_app_sentiment_index',
                'unique_together': {('district', 'year_month')},
            },
        ),
        migrations.CreateModel(
            name='TradeAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=6)),
                ('amount', models.FloatField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_amounts', to='real_estate_app.district')),
            ],
            options={
                'db_table': 'real_estate_app_trade_amount',
                'unique_together': {('district', 'year_month')},
            },
        ),
        migrations.CreateModel(
            name='TradePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=6)),
                ('price', models.FloatField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_prices', to='real_estate_app.district')),
            ],
            options={
                'db_table': 'real_estate_app_trade_price',
                'unique_together': {('district', 'year_month')},
            },
        ),
    ]
